### PR TITLE
Use official Elite Dangerous app ID

### PR DESCRIPTION
**Pull request by dudeofawesome**
This gets rid of the confusing "EDMC Discord Presence" name and replaces it with "Elite Dangerous" while sidestepping the legal concerns raised in #1.

### CODE REVIEW

**Comment by Luctins** [comment]
Maybe leave it as a Editable Text Field, or just EDMC, as it is more succint and less redundant

**Comment by dudeofawesome** [comment]
It's not really possible to make it an editable field unfortunately. 

Discord decides what text to show for the name based on info that gets provided when you create a new "game" on the Discord developer portal. Then, your app (EDMC in this case) sends a randomly generated identifier to associate the program with the listing in Discord's database. 

What I've done in this PR is to change the ID that we send to be Elite's ID instead of a custom one that was created for EDMC.

**Comment by Luctins** [comment]
Ok, fair.
Maybe just "EDMC" would be better?
I feel that the "Discord Presence" on the name is a bit redundant.

**Comment by theamazingfedex** [comment]
Bakkes Mod, a popular modding tool for Rocket League, has a plugin which does something similar to what is proposed in order to display the game title along with the detailed information. So anecdotally, it should be fine from a legal perspective.

**Comment by SayakMukhopadhyay** [comment]
First of all, I apologies for responding over a year later. This PR somehow missed my radar.
Now, jumping on to the topic.

The application ID is something that can absolutely not be changed by the user. It would defeat the whole purpose of having the application ID bundled with the plugin. If you want, you can of course, fork this project and use whatever Application ID you wish. At that point, I can claim not to be liable.

@Luctins 
> Maybe just "EDMC" would be better?
I feel that the "Discord Presence" on the name is a bit redundant.

I kinda agree, although I don't know if it would be a great idea to change it now after so long.

@theamazingfedex 
> So anecdotally, it should be fine from a legal perspective.

I am sorry but IANAL and I really can't trust anecdotal evidence. The last thing I need this year is a lawyer up my behind.

I will be closing this PR and all related PR's and I will be adding some info in the README.

**Pull request closed without merging**
