### PR TITLE
Presence text rework

### PR DESCRIPTION
**Pull request by dudeofawesome**
This PR isn't quite ready to be merged in as there are a few issues with group count reporting. Was hoping that you might have more knowledge of the E:D API and how to get a current count of how many people are in a wing or multi-crew. 

Right now, when a wing player leaves, I'm not seeing a way to get an event for that, so reported wing size can grow infinitely large.

### CODE REVIEW

**Comment by SayakMukhopadhyay** [comment]
Hi, first of all sorry for the delay in responding, Things were hectic at that time for me and I just couldn't focus on personal projects. But I am getting back into things so if you want to discuss stuff, hit me up on Discord. In the meantime I am going to migrate the plugin to Python3 to make it work with the latest EDMC.

**Comment by Poneyy** [comment]
Thank you @dudeofawesome for your pull request, I used a lot of your additions to modify the plugin as I wanted.

I found a solution for the planet name problem on landing: just save the name of the nearby planet at the time of the "ApproachBody" event and use it later in the SRV/Liftoff events.

The only way to land is to approach a Body, I think this is a good approach to the problem.

I did the same thing to get the number of the Landingpad.

The whole thing has been push on the Master branch, if you have an idea for improvement I'll thank you for it.

**Comment by SayakMukhopadhyay** [comment]
Hi, could you let me know the status of this PR? Please rebase to latest master and if you are fine with this, I can try and merge it.

**Comment by SayakMukhopadhyay** [comment]
Hi
I am going to close this PR. A lot of changes have been done in the meantime and if you still feel that your problem is unaddressed, please raise another PR and I will take a look.

**Pull request closed without merging**
