### PR TITLE
Add retro-compatibility for EDMC 3.43

### PR DESCRIPTION
**Pull request by Poneyy**
Just import tkinter or Tkinter, and precision of the character set in encode() function
I had left the plugin_start() function (replaced by plugin_start3(plugin_dir) in Python3) in the first PR.

On 3.50
2020-01-24 11_50_08-Settings

On 3.43
2020-01-24 11_57_44-Settings

### CODE REVIEW

**Comment by SayakMukhopadhyay** [comment]
Does Python 2 not support a default precision in `encode()`?

**Comment by Poneyy** [comment]
You're right, actually it works without. It seemed to me to have had an error on my side at the time of the publication by trying without using utf-8. I will test on my 2nd pc to validate.

**Comment by SayakMukhopadhyay** [comment]
ok, I will merge this once tested.

**Comment by SayakMukhopadhyay** [comment]
closes #14

**Pull request merged**
